Select date and person
zeritte/hasturizm pull request #3
Opened 2022-08-21 20:09 UTC by MAkifUNLU

![image](https://user-images.githubusercontent.com/77721632/185808957-e1615146-2f7d-413e-837c-9fdfe4e052e1.png)

giriş ekranı böyle oldu

![image](https://user-images.githubusercontent.com/77721632/185808992-e65ecba3-3cdb-494b-93d1-efa8c8f56a41.png)

uğraşıp yapamadıklarım
- Kişi seçim yerindeki borderı iptal edemedim
- seçili tarihi basamadım
- sadece günü ve ayı yazdıramadım

2022-08-22 08:47 UTC, zeritte requested changes
ekran goruntuleri icin tesekkurler, bir kac yorum biraktim onlari cozebilirsen super olur

2022-08-22 08:47 UTC, zeritte commented on src/screens/SearchScreen.js
> +  ];
bunu component disina cikarsak ve indexleri elle girsek daha iyi olur

2022-08-22 08:47 UTC, zeritte commented on src/screens/SearchScreen.js
> +            <Text style={styles.text} onPress={() => setMyDateText(Date(setDate(date)))}>
```suggestion
            <Text style={styles.text} onPress={() => setMyDateText(Date(setDate(date)).toLocaleString("tr-TR", {
  day: "numeric",
  month: "short",
  year: "numeric",
  hour: "numeric",
  minute: "2-digit"
}))}>
```
hizlica boyle bi cozum buldum.
ama olmasi gereken, burda onPress olmamasi. onun yerine bi useEffect ile her date degistiginde `myDateText` i formatlayip guncellemen

2022-08-27 08:56 UTC, MAkifUNLU commented
![image](https://user-images.githubusercontent.com/77721632/187023070-5957e73d-f2ba-43b2-bad4-d224f089c3d3.png)
Tarih seçiliyor ve yıl.ay.gün olarak yazıyor 
![image](https://user-images.githubusercontent.com/77721632/187023110-1b125b1c-307f-4b28-8a90-aae7973783ff.png)
modal selector ve date picker aynı formatta bir görünüm sağlamıyor

2022-08-31 14:51 UTC, zeritte approved these changes

2022-08-31 14:51 UTC, merged